"""empty message

Revision ID: 9493a5e1c5d6
Revises: 
Create Date: 2023-10-29 11:20:20.219145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9493a5e1c5d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teachername', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cid', sa.String(length=100), nullable=False),
    sa.Column('tid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tid'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('studentname', sa.String(length=100), nullable=False),
    sa.Column('student_gender', sa.Enum('男', '女'), nullable=False),
    sa.Column('student_id', sa.String(length=100), nullable=False),
    sa.Column('scid', sa.Integer(), nullable=True),
    sa.Column('latecount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scid'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('course')
    op.drop_table('teacher')
    # ### end Alembic commands ###
